### ISSUE TITLE
style guarding w/ elvis

### ISSUE THREAD

**Issue by Licenser** [census-instrumentation/opencensus-erlang#11]
Any objections to adding an elvis file to style-guard the source code?

**Comment by tsloughter** [comment]
Yea, that'd be good. As long as it allows lines up to 120 characters ;)

**Comment by Licenser** [comment]
who does 120c? Are we on twitter?!? I'll make a PR for that

**Comment by tsloughter** [comment]
Haha, people who aren't still using serial terminals!

--
  Tristan Sloughter
  "I am not a crackpot" - Abe Simpson
  tristan.sloughter@gmail.com


On Thu, Sep 14, 2017, at 09:38 AM, Heinz N. Gies wrote:
> who does 120c? Are we on twitter?!? I'll make a PR for that


> — You are receiving this because you commented. Reply to this email
> directly, view it on GitHub[1], or mute the thread[2].> 


Links:

  1. https://github.com/census-instrumentation/opencensus-erlang/issues/11#issuecomment-329539462

**Comment by Licenser** [comment]
You'd wonder how often I end up on a serial terminal -.- it's not even funnly :P okay 12c it is

**Comment by Licenser** [comment]
We've elvis now, closing this.
