### ISSUE TITLE
strong_rand_bytes for id generation

### ISSUE THREAD

**Issue by Licenser** [census-instrumentation/opencensus-erlang#14]
using strong_rand_bytes might cause some issues. For clarity the official documentation:

```
Generates N bytes randomly uniform 0..255, and returns the result in a binary. Uses a cryptographically secure prng seeded and periodically mixed with operating system provided entropy. By default this is the RAND_bytes method from OpenSSL.

May throw exception low_entropy in case the random generator failed due to lack of secure "randomness".
```
As I understand this, the operating systems entropy source will be used, which is a limited resource. If we drain it by creating lots of lots of id's we might end up crashing and worse crashing other system parts.

It seems like cryptographically secure ID's might not be needed and we can avoid this problem?

That said it might be  a none problem, I've been running:
```
Oops = fun(F, X) -> [crypto:strong_rand_bytes(16) ||  _ <- lists:seq(1, 1000)], io:format("~p~n", [X*1000]), F(F, X+1) end.

Oops(Oops, 0).
```

I got neither OX X nor, Linux, nor FreeBSD to crash with this just block every few million id's but that might be 'bad enough' to avoid?

**Comment by tsloughter** [comment]
Resolved by https://github.com/census-instrumentation/opencensus-erlang/pull/20
