### ISSUE TITLE
versioning issue: some tags are missing

### ISSUE THREAD

**Issue by benoitc** [census-instrumentation/opencensus-erlang#149]
Hex.pm says 0.9.1 but latest tag is 0.8.1 on git and the app.src is using "git".  Can you push the missing tag online? It's very useful to compare the differences between versions :)

**Comment by deadtrickster** [comment]
nah, 0.8.1 is the latest created. 0.9.1 just below it

**Comment by benoitc** [comment]
hrm ok . sorry for the noise then. I will blame the github ui :)
