### ISSUE TITLE
Customizable LocalEndpoint per Span

### ISSUE THREAD

**Issue by ostera** [census-instrumentation/opencensus-erlang#158]
Hi! Thanks for the work on this library.

I was wondering if you'd consider work on making the LocalEndpoint configurable _per span_, given that it isn't uncommon to run multiple services on the same Erlang distribution and they otherwise appear as within the same service name.

I've got an idea on where to start hacking, but wanted to double check to see if this is something of interest and could potentially be upstreamed 🎉 

And if it's already possible to do this but I missed it entirely, feel free to point me in the right direction and close this issue 👍

**Comment by tsloughter** [comment]
LocalEndpoint is reporter specific, right? It isn't a concern for the core span tracking.

**Comment by ostera** [comment]
Yup! Come to think of it yes. I’ll go to the zipkin reporter.
