### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by MaartenFaddegon** [census-instrumentation/opencensus-erlang#164]
Hi

There are some improvements here on Github (such as the fixed type definition 67d20751ba6bbe6600413ec367b2c268058cf9d2) that are not part of 0.9.2 which is the latest published version on Hex.

Would it be possible to make a new release on Hex?

Thanks!

**Comment by tsloughter** [comment]
Sure, I'll can publish a version today.

**Comment by tsloughter** [comment]
Published 0.9.3
