### ISSUE TITLE
Improved ocp api

### ISSUE THREAD

**Issue by tsloughter** [census-instrumentation/opencensus-erlang#22]
ocp needs to support finishing explicit spans and not just the top of the stack.

When a span is created and then finished there is no guarantee its children were properly finished, esp in the case of errors:

```erlang
ocp:start_span("hello"),
try something() %% maybe starting children!
after
  ocp:finish_span()
end.
```

Then, what is to be done with the children that weren't finished? Should `ocp:finish_span(SpanId)` result in all spans on top of `SpanId` being finished (possibly marked with an error) as well?

**Comment by tsloughter** [comment]
Should note that I think being able to close children would be the best option but requires spans being more knowledgeable about their children.

If a child is created after sending a message to another process there is no reason to assume it should be finished when the parent finishes, but if it were simply a function call then it probably should?

**Comment by tsloughter** [comment]
```
ocp:with_span("span-name", fun() -> ... end).

?ocp_with("span", 
  begin
  ...
  end).

%% or go all in with a parse transform to wrap the contents of a function :)
-is_traced().
some_fun() -> ...
```

**Comment by deadtrickster** [comment]
I think we could support both. I would probably use parse_transform :-)

**Comment by Licenser** [comment]
I kind of like the pt variant. having two ways to do the same thing can be confusing and make it harder for people to decide what's "right"

**Comment by tsloughter** [comment]
I like the pt and will work on adding that.

**Comment by tsloughter** [comment]
Issue with the parse transform (or really any of them):

If the transform creates:

```
some_fun() ->
  ocp:start_span(some_fun),
  try
    %% function body
  after
    ocp:finish_span()
  end.
```

There is no way to guarantee that the span finished is the one started at the beginning of the function since more spans could be started by what happens in the body and they may not have been finished properly.

One option is to store the span id in a variable (using the same variable name scheme from lager's transform) and explicitly finish that span:

```
some_fun() ->
  __SpanId<Module><Line> = ocp:start_span(some_fun),
  try
    %% function body
  after
    ocp:finish_span(__SpanId<Module><Line>)
  end.
```

But what should it do about the spans that may be on the stack ahead of the span being finished? Nothing? Finish them? Throw them away?

**Comment by tsloughter** [comment]
Opened a PR. But I think we should also support the function:

```
ocp:with_span("span name", fun(Context) -> ... end).
```

**Comment by adriancole** [comment]
who's down with OCP?

**Comment by tsloughter** [comment]
Yea, you know me
