### ISSUE TITLE
Reporter error handling and chaining

### ISSUE THREAD

**Issue by deadtrickster** [census-instrumentation/opencensus-erlang#25]
1. Reporters executed in `oc_reporter` genserver context without any error handling. Is this intended? I can do PR with catch-all;
2. How to chain reporters? Say I want to send spans to Zipkin, log to syslog via lager and count via Prometheus. This is not supported at the moment. I can send a PR with generic pipe_reporter which will get list of reporters from the configuration.

**Comment by deadtrickster** [comment]
I see 1. addressed in #21. Cool.

Background for 2. I think span collects enough info for tracing, metrics (why duration converted from native units?) and logs (i.e. configure "lager_reporter" to use debug level). I'm not sure about timers though. What if time window is too small for the reporter(s)? Maybe I'm missing something in the docs?

**Comment by tsloughter** [comment]
> Why duration converted from native units?

A native unit timestamp means nothing to whatever the duration is being reported to so it needs to be converted. Are you thinking we should have that conversion done by the reporter?

**Comment by tsloughter** [comment]
I'm not sure what you mean about the time window being too small. Do you mean the timer that triggers a flush of spans to the reporter?

**Comment by tsloughter** [comment]
As for multiple reporters, I'm not sure yet how we would want to do that. Should there be a default and the others are only used for a trace if the trace explicitly says to use reporter X?

@Licenser thoughts?

**Comment by tsloughter** [comment]
Checking in gitter if there is to be any expectations from the standard on supporting multiple reporters in a running system.

**Comment by adriancole** [comment]
Usually, we don't often hear about this request, except to debug and also
report. That said, finagle has this. If in java, I would do this with a
composite reporter, which has no api surface area, but would allow fan-out.

**Comment by tsloughter** [comment]
Yea, I like the idea of a composite reporter.

**Comment by Licenser** [comment]
I think both a parallel reporter and a pipe reporter do sound like a good idea, composability sounds quite useful.

**Comment by deadtrickster** [comment]
> Are you thinking we should have that conversion done by the reporter?

Yes, let's not mandate the unit. with prometheus.erl it's even more interesting as it infers units from the metric name.

> I'm not sure what you mean about the time window being too small. Do you mean the timer that triggers a flush of spans to the reporter?

Yes

> Yea, I like the idea of a composite reporter.
> I think both a parallel reporter and a pipe reporter do sound like a good idea, composability sounds quite useful.

Will do PR then
