### ISSUE TITLE
Context

### ISSUE THREAD

**Issue by tsloughter** [census-instrumentation/opencensus-erlang#32]
Thinking about making a generic context library for Erlang that handles propagation and stuff like deadlines. Already started a little, https://github.com/tsloughter/ctx 

Looking for ideas of what we can do with it besides tying it into census and other libs like Elli.

Thoughts?

**Comment by tsloughter** [comment]
This has become more important to decide now that I'm implementing tags and @deadtrickster is implementing stats.

I use ctx in [grpcbox](https://github.com/tsloughter/grpcbox) and still plan to integrate with Elli. 

The issue to solve is that we will now have spans and tags in the context. With `ctx` they'll both be stored as values in the context's values. Context lib will provide more functionality than just storing key/values, it needs to support tracking things like deadlines, so it is more than just a map.

**Comment by deadtrickster** [comment]
What was the result of that seq_id mailing list discussion? ctx lib looks like a thin wrapper for maps, what else it is supposed to do?

**Comment by tsloughter** [comment]
It is a thin wrapper around a map, yes. Point is to have a common interface/carrier to ease combining libraries and instrumenting. 

It is to have other features like deadlines as well, I haven't decided how best to handle those since I think it needs both a `ctx:done(Ctx)` option and a message sent that the deadline is met.

As for seq_trace, I've talked to Kenneth a bit off-list. I did mention tag context to him, but I don't know that they'll be an acceptable size to keep in the seq_trace context. They are limited to like 8kb, so maybe, we'll see.

**Comment by aramallo** [comment]
Hi @tsloughter, I am just starting to look at OC. I am guessing  `ctx` assumes the context will be shared between erlang processes/nodes and thus makes sense for the structs to be implemented as records. 

Do you guys have the need to cross language boundaries with the Context so that we could rethink it as a more friendly data struct to be encoded in other formats e.g. JSON, MsgPack, etc? This would mean replacing (a) replacing all the records for maps or (b) having a `ctx:to_map/1` and `ctx:from_map/1` as a intermediate step to do the encoding in the selected format.

**Comment by tsloughter** [comment]
@aramallo propagating span and tag context is separate from the use of `ctx`. Those are encoded to a text or binary format per the opencensus spec that each language with opencensus support can decode and use.

https://github.com/census-instrumentation/opencensus-erlang/blob/master/src/oc_trace_context_binary.erl
https://github.com/census-instrumentation/opencensus-erlang/blob/master/src/oc_trace_context_headers.erl
https://github.com/census-instrumentation/opencensus-erlang/blob/master/src/oc_tag_ctx_binary.erl

`ctx` is simply for tracking them through Erlang calls. In the case of `ocp` it isn't even used and instead the process dictionary is used in its place to track span and tag contexts.

**Comment by aramallo** [comment]
@tsloughter Ahh cool, I will look into that, thanks!
