### ISSUE TITLE
Sampling

### ISSUE THREAD

**Issue by des75** [census-instrumentation/opencensus-erlang#34]
Hi,

I have a question about how do sampling works.
I've added spans counter in my reporter to compare total count of spans and count of spans when I use sampling, and found that sampler doesn't affect on it.

my sampling config:
```
{sampler, {oc_sampler_probability, [
     {probability, 0.5}
]}}
```

With this config I expect to see count of spans will be about a 2 times less than total count, but I got the identical numbers.

Is this a correct behaviour, or I doing something wrong?

**Comment by tsloughter** [comment]
Hm, that looks correct, we test this in `oc_sampler_SUITE`.

Just be sure can you verify that `application:get_env(opencensus, sampler).` returns that sampler config when running?

**Comment by des75** [comment]
The issue is already solved for me. Here is the related PR:
https://github.com/census-instrumentation/opencensus-erlang/pull/35

**Comment by tsloughter** [comment]
Aah, ok.

**Comment by des75** [comment]
Sorry for misinformation, I solved that issue by another workaround.

Seems, for some reason the field `enabled` is being ignored when creating traces and spans. It means no matter which value will be in the `enabled` field, the spans anyway will be created and reported.

I've used something like this:
```
...
Context = ocp:context(),
if Context#trace_context.enabled -> ocp:start_span(SpanName);
   true -> undefined
end
...
```
It worked, but I think it shouldnt be so explicit.

**Comment by tsloughter** [comment]
@des75 there are a number of changes to how the enabled works, and the api in general, in my PR #49 that you'll want to take a look at.

Hopefully will be merged early in the week and be a fairly stable api (at least for spans) after this.

**Comment by tsloughter** [comment]
The new code should properly implement the logic described in the spec https://github.com/census-instrumentation/opencensus-specs/blob/master/trace/Sampling.md -- except that a "span scoped" sampler is not yet supported.

This means if the span is the child of a remote span and the sampler is the probability sampler it will stay sampled if the remote parent is enabled. Setting that it is a remote span is done with options to span creation, `#{remote_parent => true}` and is something you'd set if starting a span at the entry point of an HTTP request or similar.

If it is a local parent, it keeps the parent decision.

And to give an idea of how the api has changed, this is what your workaround would look like:

```
...
SpanCtx = ocp:current_span(),
if (SpanCtx#span_context.trace_options band 1) =/= -> ocp:with_child_span(SpanName);
   true -> undefined
end
...
```

**Comment by deadtrickster** [comment]
Finally synced our code with master, closing this.
