### ISSUE TITLE
Zipkin reporter

### ISSUE THREAD

**Issue by deadtrickster** [census-instrumentation/opencensus-erlang#40]
We have (basic) Zipkin reporter. It works ok and I'm thinking about creating PR for it. Not sure about http client though. It can be httpc, hackney, gun or whatever. Ours is httpc for the moment.

**Comment by tsloughter** [comment]
@deadtrickster I used hackney for the google stackdriver reporter.

Do we want to include them in this repo or keep them as separate deps and list them in the readme?

**Comment by deadtrickster** [comment]
I don't mind including exporters/importers (perhaps even want this), but, as discussed, I would go with configurable http adapters. Most of the times is calling a function with Method, URL, Headers and (optionally) Body. We dodge many holy-wars this way :-)

**Comment by deadtrickster** [comment]
#53
