### ISSUE TITLE
Handling orphaned spans

### ISSUE THREAD

**Issue by tsloughter** [census-instrumentation/opencensus-erlang#54]
In the event `finish` is never called for a span context the span data will currently live on forever in the ets table.

There should be either a new process that does a clean operation on the table, or could have it happen when the reporter runs, and have it check spans against a configurable TTL, deleting those that are too old and deemed abandoned. 

Optionally the pid each span was created in could be added to the data and used to know if a span should be finished/removed. There could even be a monitor to track the span's owner and finish it on a down message.

I'd argue for just the TTL, it is the simplest and least likely to result in much overhead or flooded process. But there may be something to supporting a span that exists for the life of a process, being an optional way of creating a span:

```erlang
oc_trace:spawn_span(<<"name">>, fun() -> i_get_traced end)
```

Where `oc_trace:spawn` is basically:

```erlang
spawn_span(Name, Fun) ->
  erlang:spawn(fun() ->
    SpanCtx = oc_trace:start_span(Name),
    {Pid, Ref} = erlang:spawn_monitor(fun() ->
                          ocp:with_span(SpanCtx),
                          Fun()
                        end),
    receive
        {'DOWN' ...} ->
            oc_trace:finish_span(SpanCtx)
    end
  end).
```

Or have a single/pool of processes responsible for doing the monitoring and just send it a message instead of having to spawn twice.

**Comment by deadtrickster** [comment]
in face spawn_span can also handle Parent context transfer. It's one of the options. Reasonable default? TTL sounds good too, then just run match spec.

**Comment by hauleth** [comment]
By default there should be a monitor that will end span when the process dies.

**Comment by hauleth** [comment]
I just found case, where we *must* monitor process to handle finishing spans - process failures. In general Erlang encourages users to just kill process in case of unexpected data, and if that happen in application monitored by Opencensus then we will loose that trace together with it's information as there is no way to get information from process dictionary after the process is dead. So we will end with handling trace that has no way to mark itself as dead and that it was abandoned due to owner failure.

**Comment by tsloughter** [comment]
@deadtrickster were you working on this? If not I can grab it.

@hauleth I still think it shouldn't be the default. Closing the span in the same process is necessary to get an accurate end time, so it doesn't simplify instrumentation for a user, and adds overhead even if it is usually going to be negligible.

But I'm thinking we need tracer to be configurable, similar to what I'm trying with stat recording. Then instead of having to do like `ocp:with_child_spawn_and_monitor` you can either set the application env var for which tracer to use or choose it at the time of trace creation (not sure what that api would look like).

**Comment by hauleth** [comment]
I would go with `cop:with_child_span(Name, Attributes, Options)` and `cop:with_child_span(Name, Attributes, Func, Options)` where `Options :: [option]` and `option :: monitor`. This would give the best "experience" in my opinion.

**Comment by hauleth** [comment]
@tsloughter another pro of monitoring by default (because the idea is that ending ended span will be no-op) is that you will be able to automatically mark spans in failed processes as failed, even if user do not handle such logic on their own. This is something big enough to provide monitoring by default IMHO, so common case will be handle automatically instead of relying on user.

**Comment by tsloughter** [comment]
@hauleth I was thinking we can handle marking as failed without a monitor since we'll have the checker process that finds spans older than some TTL. The pid will be included in the table so the TTL check can also see if the process is alive. If the process isn't alive the span is marked as failed.

**Comment by tsloughter** [comment]
If it is monitored you have the same issue.

**Comment by hauleth** [comment]
[`metrics`](https://github.com/benoitc/erlang-metrics) library uses monitors to [watch over processes with counters](https://github.com/benoitc/erlang-metrics/blob/3ea572b5b6ca4a3e5dfc12009058f8771baf5789/src/metrics_process_tracker.erl).

**Comment by tsloughter** [comment]
If you rely only on the monitor you can safely assume `normal` exit status means success. I assumed even if you were monitoring you'd want to be closing spans manually as well, since a process often has multiple spans and it gives you better timing, and saves on the chance of overloading the watchers, so you still don't know if was simply forgotten.

**Comment by hauleth** [comment]
@tsloughter that is why I suggested making `oc_trace:finish_span/1` idempotent, aka this code

```elrang
Span = oc_trace:start_span("Foo", Ctx),
true = oc_trace:finish_span(Span),
true = oc_trace:finish_span(Span).
```

Will result with only one span reported (first one) and the second call to `oc_trace:finish_span/1` will be noop. This will allow us to finish traces and do not care if it will be then "cleaned again" by monitor. Unfortunately IIRC Erlang do not have any way to force using returned value which would provide us another possible solution for this problem.

**Comment by tsloughter** [comment]
Na, I was just saying that when the watcher gets a down message for a process with reason other than `normal` even in the monitor by default version it isn't guaranteed to mean it wasn't a success and simply forgotten to finish the span.

**Comment by hauleth** [comment]
It is better to mark them as failures and make user to handle them instead of trying to deduce what "user had in mind" or to lose unclosed spans.

**Comment by deadtrickster** [comment]
we forgot to finish spans here sometimes, best detected by memory graph :-)

**Comment by hauleth** [comment]
I think that memory exhaustion is much more problematic than potential performance loss due to monitoring.

**Comment by tsloughter** [comment]
Memory exhaustion shouldn't be a problem since we'll be sweeping for orphaned spans.

I'd like to get that added today since this'll be going into production at my work soon. @deadtrickster did you do similar at work and have something you can PR or should I make one?

**Comment by hauleth** [comment]
I can prepare example of what I have in mind. 

--
Łukasz Jan Niemier

**Comment by hauleth** [comment]
Simplest implementation (not tested yet):

```erlang
-module(oc_trace_srv).

-behaviour(gen_server).

%% PUBLIC API
-export([monitor_span/1]).

%% PRIVATE API
-export([start_link/0, init/1, handle_info/2, handle_call/3, handle_cast/2]).

%% PUBLIC API IMPL
monitor_span(Span) ->
    gen_server:call(?MODULE, {watch, self(), Span).

%% PRIVATE API IMPL
start_link() ->
    gen_server:start_link({local, ?MODULE}, ?MODULE, [], []).

init(Opts) ->
    {ok, Opts}.

handle_call({watch, Pid, Span}, _Ref, State) ->
    erlang:monitor(process, Pid),
    NewState = maps:update_with(Pid,
                                fun (List) -> [Span | List] end,
                                [Span],
                                State),
    {reply, ok, NewState}.

handle_cast(_Msg, State) -> {noreply, State}.

handle_info({'DOWN', _Ref, process, Pid, _Status}, State) ->
    case maps:take(Pid, State) of
        error -> {noreply, State};
        {_Spans, NewState} ->
            logger:info("Process ~p died, cleaning up", [Pid]),
            clean(Spans),
            {noreply, NewState}
    end.

%% HELPER FUNCTIONS
clean(Spans, normal) ->
    [finish_with_status(Span) || Span <- Spans],
    ok.

finish_with_status(Span, normal) ->
    oc_trace:finish_trace(Span);
finish_with_status(Span, _Status) ->
    oc_trace:finish_trace(oc_trace:set_status(2, "Unknown error", Span)).
```

And only change to `oc_trace` is:

```diff
diff --git a/src/oc_trace.erl b/src/oc_trace.erl
index 9a3a653..aaf2361 100644
--- a/src/oc_trace.erl
+++ b/src/oc_trace.erl
@@ -175,6 +175,7 @@ new_span_(Name, Parent=#span_ctx{trace_id=TraceId,
                  name=Name,
                  attributes=#{}},
     ets:insert(?SPAN_TAB, Span),
+    oc_trace_srv:monitor_trace(Span),

     Parent#span_ctx{span_id=SpanId};
 new_span_(_Name, Parent, _Kind, _RemoteParent) ->
```

**Comment by deadtrickster** [comment]
yes, I have this branch with a gen server and stuff, but I don't want to put you guys on hold. I can look at it on friday but most likely weekend

**Comment by tsloughter** [comment]
My crack at it, https://github.com/census-instrumentation/opencensus-erlang/pull/118

**Comment by tsloughter** [comment]
Closing this since we have the simple implementation complete and should discuss the more exact ideas in their own issues.

I still kicking it around in my head and may open one for something like `start_span_monitor/3`.
